more scaffolding code

diff --git a/zwe1b0/zwe1b0config b/zwe1b0/zwe1b0config
--- a/zwe1b0/zwe1b0config
+++ b/zwe1b0/zwe1b0config
@@ -1,2 +1,23 @@
 #!/bin/sh
+. zbrewsetenv
+
+zweRoot="${ZBREW_WORKROOT}/config/zwe1b0"
+mkdir -p "${zweRoot}"
+rc=$?
+if [ $rc -gt 0 ]; then
+	echo "Unable to create configuration directory: ${zweRoot}"
+	exit $rc
+fi
+
+cd "${mydir}/generate"
+steps=`echo *`
+cd $OLDPWD
+for step in ${steps}; do
+	script="${zweRoot}/${step}.sh"
+	"${mydir}/generate/${step}" ENABLE "${script}"
+	if [ $? -gt 0 ]; then
+		exit $?
+	fi
+done
+
 exit 0
